name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 14
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
