name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    env:
      STRIPE_SK: ${{ secrets.STRIPE_SK }}
      NEXT_PUBLIC_STRIPE_PK: ${{ secrets.NEXT_PUBLIC_STRIPE_PK }}
    if: ${{ !contains(github.event.head_commit.message, 'wip:') }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build App for testing
        run: yarn build
      - name: Lint app
        run: yarn lint
