name: CI
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'wip:') }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1
        with:
          node-version: 14
      - name: Install dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Build App for testing
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Lint app
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: lint
